# Generated by Django 5.0 on 2023-12-27 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sales",
            new_name="Sale",
        ),
    ]
