[tool.poetry]
name = "full-stack-web-study-backend"
authors = []
description = ""
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.11"
djangorestframework = "^3.14.0"
mysqlclient = "^2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
